version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-pip:
    executor: python/default
    steps:
      - checkout
      - python/load-cache:
          key: pip
      - run:
          command: |
            pip install numpy
            sudo apt-get install libproj-dev proj-data proj-bin
            sudo apt-get install libgeos-dev
            pip install cython
            pip install cartopy
            pip install -r requirements.txt
          name: get-dependencies 
      - python/save-cache:
          key: pip
      - run:
          command: python -m unittest discover -v -s tests/
          name: Test

 
workflows:
  main:
    jobs:
      - build-pip