version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-pip:
    executor: python/default
    steps:
      - checkout
      - python/load-cache:
          key: pip
      - run: pip install -r requirements.txt
      - python/save-cache:
          key: pip
      - run:
          command: ./manage.py test
          name: Test

workflows:
  main:
    jobs:
      - build-pip