# This is a basic workflow to help you get started with Actions

name: Codecov

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  workflow_dispatch:  # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Codecov
      uses: codecov/codecov-action@v1.5.2
