# This is a basic workflow to help you get started with Actions

name: Codecov

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  workflow_dispatch:  # Allows you to run this workflow manually from the Actions tab

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Codecov
      uses: codecov/codecov-action@v1.5.2

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.6

    - name: Generate coverage report
      run: |
        pip install coverage
        coverage run --source=xmca -m unittest discover -v -s tests/
        coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: ./coverage.xml
